services:
  - type: web
    name: nifty-oi-bot
    plan: free    # <--- FREE TIER (no payment needed)
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    autoDeploy: true
    envVars:
      - key: EMAIL_FROM
        value: "pranavwanderer@gmail.com"

      - key: EMAIL_TO
        value: "chakorlokur75@gmail.com"

      - key: EMAIL_PASSWORD
        value: "wvnefmgjharlihen"

      - key: WHATSAPP_ENABLED
        value: "False"